services:
  frontend:
    build: .
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:80" # keeps your existing port, maps to nginx inside
    # depends_on:
    #   - gateway
    # external_links:
    #   - gateway

networks:
  default:
    name: crowd-management-network
    external: true
